### ISSUE TITLE
has this repository stopped being maintained?

### ISSUE THREAD

**Issue by raphaelkieling** [ConsoleTVs/AdonisWebsok#4]
I'm using this lib to my project but we have problems to use reconnection. Has this lib stopped being maintained??

**Comment by ConsoleTVs** [comment]
Hello @raphaelkieling, Nice observation.

I did create this library as a way to get around my needs for a certain project. My intention is to use it for my needs. I am well aware of the possible issues this project might have. I am more than welcome to merge any pull requests that you make in order to implement your needs (eg. reconnection). However, I will probably not add more stuff of my own for now. Specially since adonis is undergoing a major rework and will go out of beta soon :)

**Comment by raphaelkieling** [comment]
Yes, i understand, though thanks for the start the project and study around the adonis communication to created a this library.
